config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'users/index'
    get 'users/show'
  end
  resources :posts, only: [:show, :index]

  root 'posts#index'

  namespace :admin do
    resources :posts 
    resources :users
  end

  devise_for :users

  # get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'pages' do
    get 'about'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  # Active Storage from Rails 5
  has_one_attached :thumbnail
  has_one_attached :banner

  # Action text from Rails 6
  has_rich_text :body

  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 25 }

  self.per_page = 10

  extend FriendlyId
  friendly_id :title, use: :slugged

  def optimized_image(image,x,y)
    image.variant(resize_to_fill: [x, y]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: { member: 0, moderator: 1, admin: 2 }, _default: 0
  validates :first_name, :last_name, :email, :password, :password_confirmation, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :is_admin!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1 or /posts/1.json
  # def show
  #   views = @post.views + 1
  #   @post.update(views: views)
  # end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :banner, :thumbnail)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :is_admin!     

    private

    def is_admin!
        redirect_to root_path, alert: "Permission denied" unless current_user&.admin?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    # helper_method :is_admin!

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password])
    end

    # def is_admin!
    #     redirect_to root_path unless current_user&.admin?
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
  
    # GET /posts or /posts.json
    def index
      @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
    end
  
    # GET /posts/1 or /posts/1.json
    def show
      views = @post.views + 1
      @post.update(views: views)
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :body, :banner, :thumbnail)
      end
  end
  

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/posts/_form.html.erb
<%= form_with model: [:admin, post] do |f| %>
  
  <div class="form-inputs">
    <p><%= f.label :title, class: 'form-control' %></p>
    <p><%= f.text_field :title, class: 'form-control string' %></p>
    <br>
    <p><%= f.label :thumbnail, class: 'form-control' %></p>
    <p><%= f.file_field :thumbnail %></p>
    <br>
    <p><%= f.label :banner, class: 'form-control' %></p>
    <p><%= f.file_field :banner %></p>
    <br>
    <p><%= f.label :body, class: 'form-control' %></p>
    <p><%= f.rich_text_area :body %></p>
  </div>

  <div class="form-actions">
    <p><%= f.button :submit, class: 'btn btn-outline-primary' %></p>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: 'btn btn-outline-primary' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-outline-primary' %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>
 
<table class="table">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Owner</th>
    <th scope="col">Views</th>
    <th scope="col">Coments</th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.user.first_name %> <%= post.user.last_name %></td> 
      <td><%= post.views%></td>
      <td>0 coments</td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
      <td><%= link_to 'Destroy', admin_post_path(post), data: {confirm: "Are you sure?"},
                                      :method => :delete %></td>
    </tr>
  <% end %>
</table>

<div class="digg_pagination">
  <%= will_paginate @posts, :container => false %>
</div>
 
<br />
 
<%= link_to 'New post', new_admin_post_path, class: 'btn btn-outline-primary' %>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-outline-primary' %>

app/views/admin/posts/show.html.erb
<%
=begin%>
 <div style="width: 100%; height: 300px; overflow-y: hidden">
  <%= image_tag(@post.banner, style: 'width: 100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width: 100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>  
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.first_name %> <%= @post.user.last_name %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4">
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div> 
<%
=end%>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <%= user.first_name %><br/>
  <%= user.last_name %><br/>
  <%= user.email %><br/>
  <hr>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.first_name %></h1>
<h1><%= @user.last_name %></h1>
<h5><%= @user.email%></h5>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
      <% if current_user&.admin?%>
        <li class="nav-item">
        <a class="nav-link" href="<%= admin_posts_path %>">Posts</a>
      </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
        <% if current_user %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account settings</a>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Logout", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
                </div>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Signup", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Signin", new_user_session_path, class: 'nav-link' %>            
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <div class="alert alert-danger">
        <% elsif type == 'notice' %>
          <div class="alert alert-success">
        <% end %>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class='container'>
    <div class="jumbotron">
        <h1 class="display-4">About me</h1>
        <div class="row">
            <p style="text-align: justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique erat dui, accumsan blandit enim condimentum at. Etiam quam justo, imperdiet vel tempor sed, tempus ac odio. Curabitur posuere dignissim nulla elementum laoreet. Quisque consequat odio non efficitur ultrices. Aliquam massa lectus, posuere ac sapien ac, rhoncus cursus lacus. Suspendisse lobortis neque in lectus dapibus, vitae varius elit pellentesque. Vivamus at ligula nec ipsum volutpat mollis.
            </p>
            <p style="text-align: justify">
                Morbi vel turpis sed elit faucibus suscipit. Nunc euismod lectus a magna viverra, nec condimentum metus mollis. Ut iaculis dolor sit amet vulputate suscipit. In eleifend bibendum sollicitudin. Maecenas eu tellus sem. Nam convallis enim eu orci fringilla fermentum. Aliquam et iaculis mi, non volutpat ipsum. In et laoreet sapien, id fringilla nisl. Aliquam dictum semper aliquam. Aenean non vestibulum neque, accumsan iaculis risus. Proin sed augue ut nulla dignissim faucibus id vitae sem. Aliquam scelerisque volutpat odio in faucibus. Nullam mollis commodo urna lobortis volutpat. Sed turpis augue, rhoncus nec nulla quis, sagittis vestibulum lorem. Vivamus interdum ut eros a ornare.
            </p>
            <hr class="my-4"/>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" onclick="window.location.href = 'https://github.com';" class="btn btn-secondary">Github</button>
            <button type="button" onclick="window.location.href = 'https://youtube.com';" class="btn btn-secondary">Youtube</button>
            <button type="button" onclick="window.location.href = 'https://facebook.com';" class="btn btn-secondary">Facebook</button>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="row">
    <div class="card mb-3">
      <img class="card-img-top"
      src="<%= url_for post.optimized_image(post.thumbnail, 1920, 600 ) %>"
      alt="Blog Image Card"
      />
      <div class="card-body">
        <div class="card-title">
          <%= link_to post.title, post %>
          <% if current_user&.admin? %>
            <%= link_to 'Edit', edit_admin_post_path(post), class: "badge badge-primary" %>
            <%= link_to 'Destroy', admin_post_path(post), data: {confirm: "Are you sure?"},
                                      :method => :delete, class: "badge badge-danger" %>
          <% end %>
        </div>
        <div class="card-text">
          <%= post.body.to_plain_text.truncate_words(50) %>
        </div>
        <div class="card-text">
          <small>
            <%= post.updated_at.strftime("%A, %B %e, %Y") %> by 
            <%= post.user.first_name %> <%= post.user.last_name %> | <%= pluralize(post.views, "View") %> | 0 coments
          </small>          
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="digg_pagination">
  <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/show.html.erb
<div style="width: 100%; height: 300px; overflow-y: hidden">
  <%= image_tag(@post.banner, style: 'width: 100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width: 100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %> 
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.first_name %> <%= @post.user.last_name %> | <%= pluralize(@post.views, "View") %>
        <% if current_user&.admin? %>
            <%= link_to 'Edit', edit_admin_post_path(@post), class: "badge badge-primary" %>
            <%= link_to 'Destroy', admin_post_path(@post), data: {confirm: "Are you sure?"},
                                      :method => :delete, class: "badge badge-danger" %>
          <% end %> 
      </p>
      <hr class="my-4">
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>